[project]
name = "app"
version = "1.0.0"
description = "Python simple todo and blog app"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
